version: '5.1'

services:
    to-do-list-api:
        container_name: to-do-list-api
        image: to-do-api
        ports:
            - "8000:8000"
        build: 
            context: .
            dockerfile: Dockerfile

